# Generated by Django 4.2.6 on 2023-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('D', 'Done'), ('P', 'In  progress'), ('TBD', 'Not done')], default='TBD', max_length=3)),
            ],
        ),
    ]
